logging:
  level: INFO
  loggers:
    com.maf: DEBUG

server:
 applicationContextPath: /
 adminContextPath: /
 applicationConnectors:
  - type: http
    port: 8080
 adminConnectors:
  - type: http
    port: 8081

hotels_providers:
 - http://localhost:8081/ping #this one stand for best hotels
 - http://localhost:8081/ping #this one stand for crazy hotels